diff_drive_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]
    wheel_separation: 0.5
    wheel_radius: 0.1
    cmd_vel_timeout: 0.5
    publish_rate: 50
